services:
  mart_database:
    container_name: postgres_mart_db
    image: postgres:17

    env_file:
      - /var/secrets/mart-app.env

    ports:
      - "5434:5432"

    volumes:
      - postgres_mart_db:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

  mart_app:
    build: .
    container_name: mart_app

    env_file:
      - /var/secrets/mart-app.env

    ports:
      - "1200:1200"

    environment:
      DATASOURCE_URL: jdbc:postgresql://database:5432/mart_app

volumes:
  postgres_mart_db:
